global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "elasticsearch"
    static_configs:
      - targets: ["elasticsearch:9200"]

  - job_name: "logstash"
    static_configs:
      - targets: ["logstash:9600"]

  - job_name: "kibana"
    static_configs:
      - targets: ["kibana:5601"]
